config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :lessons
  resources :categories
  resources :bookings
  resources :reviews

  get '/search', to: "search#index"

  root 'welcomes#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :instructor, -> { where role: "instructor" }, class_name: "User"
  has_many :bookings
  has_many :users, through: :bookings
  belongs_to :category
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/user.rb
class User < ActiveRecord::Base
  scope :instructor, -> (boolean = true) { where(role: "instructor") }
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
  has_many :lessons, through: :bookings
  has_many :reviews

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_ransack_form_variables

def set_ransack_form_variables
  q = params[:q]
    @lessons = Lesson.search(title_cont: q).result
    @categories = Category.search(name_cont: q).result
    @users = User.search(name_cont: q).result
end

@categories = Category.all

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :image, :role, :name, :biography) }
 end
end

app/controllers/bookings_controller.rb
class BookingsController < ActionController::Base

  def index
    @bookings = Booking.all
    respond_to do |format|
      format.html
      format.json { render json: @bookings }
    end
  end

  def create
    @booking = Booking.create(booking_params)
    render json: @booking, status: :created
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    head :no_content, status: :ok
  end

  private
  def booking_params
    params.require(:booking).permit(:user_id, :lesson_id, :status)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @q = Category.ransack(params[:q])
    @categories = @q.result(distinct: true)
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    @q = Lesson.ransack(params[:q])
    @lessons = @q.result(distinct: true)
  end

  def show
    @lesson = Lesson.find(params[:id])
    @user = current_user

    unless @user.nil?
      @booking = @user.bookings.where(lesson_id: @lesson.id)
    end

    if @booking.nil? || @booking.empty?
      @spaces_left = @lesson.capacity
    else
      @status = @booking.first.status
      @spaces_left = @lesson.capacity-@lesson.bookings.length
    end
    if @spaces_left.nil? == false && @spaces_left > 0
      @lesson_has_space = true
    end

    unless @user.nil?
      @booking = @user.bookings.where(lesson_id: @lesson.id)
    end

    # @no_booking = @booking.empty?
    # if @no_booking
    #   nil
    # else
    #   @status = @booking.first.status
    # end
    @space_left = @lesson.capacity-@lesson.bookings.length
  end

  def new
    @lesson = Lesson.new
    @categories = Category.all
  end

  def create
    @lesson = Lesson.create(lesson_params)
    @lesson.instructor_id = current_user.id
    @lesson.save
    redirect_to lessons_path
  end

  def edit
    @lesson = Lesson.find(params[:id])
    @categories = Category.all
  end

  def update
    @lesson = Lesson.find(params[:id])
    @lesson.update(lesson_params)
    redirect_to lessons_path
  end


  private
  def lesson_params
    params.require(:lesson).permit(:title, :description, :category_id, :capacity, :start_time, :end_time, :date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.order("RANDOM()").limit(5)
  end

  def show
    @review = Review.find(params[:id])
    @user = current_user
  end

  def new
    @review = Review.new
    @lessons = Lesson.all
  end

  def create
    @review = Review.create(review_params)
    @review.user_id = current_user.id
    @review.save
    redirect_to reviews_path
  end

  def edit
    @review = review.find(params[:id])
    @categories = Lesson.all
  end

  def update
    @review = review.find(params[:id])
    @review.update(review_params)
    redirect_to reviews_path
  end


  private
  def review_params
    params.require(:review).permit(:rating, :comment, :lesson_id, :capacity)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @lessons = Lesson.all
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @user = User.find(params[:id])
    @lessons = Lesson.all
    @bookings = Booking.all
    @bookings_as_client = @bookings.where(user_id: @user.id)
    @lessons_as_instructor = @lessons.where(instructor_id: @user.id)
    @review = Review.new
  end


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h2>I am the index.html.erb file for categories</h2>

<% @categories.each do |category| %>
  <p><%= link_to category.name, category_path(category) %></p>
<% end %>

app/views/categories/show.html.erb
<div class="category-container">
  <div class="header_container">
    <h1 class="categories_header"><%= @category.name %></h1></div>
    <div class="banner" style="
    background-image: url(<%=@category.image %>);
    background-size: cover;
    width: 100%;
    height: 80%;
    position: fixed;
    top: 100px;
    background-color: #707070;
    "
    >
  </div>
  <div class="lessons-container">
    <div class="container">
      <p class= "category_description"><%= @category.description %></p>
      <% @category.lessons.each do |lesson| %>
      <div class="lesson-box">
        <h4> <%=lesson.title  %></h4>
        <p>Instructor: <%=lesson.instructor.name  %> </p>
        <%= link_to "more info", lesson_path(lesson) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :body || "<body>" %>
  <title>GetFit</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <link href='http://fonts.googleapis.com/css?family=Monda:700' rel='stylesheet' type='text/css'>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">GetFit</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, category_path(category.id) %></li>
              <% end %>
            </ul>
          </li>
          <li><%= link_to "Instructors", users_path %></li>
          <li><%= link_to "Reviews", reviews_path %></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
      <li><%= link_to "My Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li><%= link_to "Register", new_user_registration_path %></li>
      <% end %>

      <li><div class="form-group">
        <%= form_tag('/search', method: :get, class: "navbar-form navbar-right") do %>
        <%= text_field_tag :q, nil, class:"form-control", placeholder:'Search' %>
        <button type="submit" class="btn btn-default">Submit</button>
        <% end %>
      </div></li>
    </ul>

  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<!-- <p class="notice"><%= notice %></p> -->
<!-- <p class="alert"><%= alert %></p> -->

<%= yield %>

</body>
</html>

app/views/lessons/_form.html.erb
<div class="form-container"><%= form_for(@lesson) do |f| %>

  <div class="letter-field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="letter-field form-group">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>

  <div class="letter-field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>


  <div class="field">
    <% @categories.each do |category| %>
      <%= f.radio_button(:category_id, category.id.to_int) %>
      <%= f.label(:category, category.name) %>
    <% end %>
  </div>

  <div class="letter-field form-group">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="letter-field form-group">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>

  <div class="letter-field form-group">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>

  <div class="actions">
    <%= f.submit 'Go', :class => "button" %>
  </div>
<% end %>
</div>

app/views/lessons/index.html.erb
<h2>Lessons</h2>

<% if current_user && current_user.role == 'instructor'%>
  <p><%= link_to 'NEW Lesson', new_lesson_path %></p>
<% end %>

<% @lessons.each do |lesson| %>
  <p><%= link_to lesson.title, lesson_path(lesson) %></p>
<% end %>

app/views/lessons/show.html.erb
<div class="lesson-view-page">
  <div class="lesson-view-container">

    <h2><%= @lesson.title %></h2>

    <% if @spaces_left == 0 %>
      <h4>This class is fully booked! Go <%= pnk_to "back", lessons_path %> to view other lessons</h4>
    <% end %>

      <p><strong>Description:</strong> <%= @lesson.description %></p><br>
      <p><strong>Instructor:</strong> <%= @lesson.instructor.name %></p><br>
      <p><strong>Capacity:</strong> <%= @lesson.capacity %></p><br>
      <p><strong>Date:</strong> <%= Date::MONTHNAMES[@lesson.date.month] %> / <%= @lesson.date.day %> / <%= @lesson.date.year %></p><br>
      <p><strong>Time:</strong> <%= @lesson.start_time.hour %>:<%= @lesson.start_time.min %> - <%= @lesson.end_time.hour %>:<%= @lesson.end_time.min %></p><br>
      <% if current_user %>
        <% unless @booking.empty? %>
          <p>Your registration status: <%= @status %></p>
        <% end %>
      <% end %>

    <% if current_user %>
      <% if @booking.empty? %>
        <button id="apply-to-join" data-id="<%= @lesson.id %>" data-user="<%= @user.id %>">Apply to join now</button>
      <% end %>
    <% end %>
    </div>
    <div class="lesson-image-show">
      <%= image_tag "https://s3-eu-west-1.amazonaws.com/fitnessproject/slide4.jpg" %></div>
  
  
  <div class="placeholder-lesson-image"><%=  %></div>
</div>

app/views/reviews/_form.html.erb
<div class="form-container"><%= form_for(@review) do |f| %>

  <div class="field">
    <% (1..5).each do |number| %> 
      <%= f.radio_button(:rating, number) %>
      <%= f.label(:rating, number) %>
    <% end %>
  </div>

  <div class="letter-field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>


  <div class="field">
    <%=f.collection_select :lesson_id, Lesson.all, :id, :title  %>
  </div>

  <div class="actions">
    <%= f.submit 'Go', :class => "button" %>
  </div>
<% end %>
</div>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/index.html.erb
<div class="review-container">
  <h4>What our students have to say:</h4>

  <% @reviews.each do |review| %>
    <blockquote>
      <p><%= review.comment %></p>
       <footer><%= review.user.name %>,<cite title="Source Title"> <%= review.lesson.title %></cite></footer>
    </blockquote>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h2>Write a new review</h2>

<%= render 'form' %>

app/views/search/index.html.erb
<div class="search-container">
<h4>Lessons</h4>
<% if @lessons.present? %>
  <% @lessons.each do |lesson| %>
        <%= link_to lesson.title, "lessons/#{lesson.id}" %>
  <% end %>
<% else %>
<h5>There are no lessons matching your search term.</h5>
<% end %>

<h4>Categories</h4>
<% if @categories.present? %>
  <% @categories.each do |category| %>
        <%= link_to category.name, "categories/#{category.id}" %>
  <% end %>
<% else %>
<h5>There are no categories matching your search term.</h5>
<% end %>

<h4>Instructors</h4>
<% if @users.present? %>
  <% @users.each do |user| %>
    <% if user.role == "instructor" %>
        <%= link_to user.name, "users/#{user.id}" %>
    <% else %>
    <h5>There are no instructors matching your search term.</h5>
    <% end %>
  <% end %>
<% else %>
<h5>There are no instructors matching your search term.</h5>
<% end %>
</div>

app/views/users/index.html.erb
<div class="instruct-header"><h2>Instructors</h2></div>
<div class="container">
<% @users.each do |user| %>
  <% if user.role == 'instructor' %>
  <div class="tile">
    <div class="instructor-image"><%= image_tag user.image %></div>
    <p><%= link_to user.name, user_path(user) %></p>
    </div>
  <% end %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="lesson-view-page">
  <div class="user-name">
    <h3><%= @user.name %></h3>
  </div>
  <div class="user-image lesson-view-container">
    <%= image_tag @user.image %>
  </div>

  <div class="user-content lesson-image-show">
    <p><%= @user.biography %></p>
  </div>

</div>

<% if @user.role == "instructor" && current_user == @user %>
<div class="lesson-bookings-header">
  <strong>Bookings for your lessons:</strong>
  Click the buttons to confirm the student's booking, then once the class is over, click again to mark them as attended.  Only then will they be able to write you a review!
</div>
<% end %>


<div class="instructor-view-bookings">
<!-- if viewing an instructor page, show all the lessons they teach -->
<% @lessons_as_instructor.each do |lesson| %>
  <table class="table table-striped">
      <thead><h4><em><%= link_to lesson.title, "/lessons/#{lesson.id}"  %><% if current_user == @user %><%= link_to " - edit", "/lessons/#{lesson.id}/edit"  %><% end %></em></h4>
          <% if current_user && current_user == @user %>      
          <tr>
              <th></th>
              <th>Client Name</th>
              <th>Booking Status</th>
          </tr>
          <% end %>
      </thead>
      <!-- if instructor logged in and viewing their own show page display bookings -->
      <% if current_user && current_user == @user %>
        <tbody>
          <% lesson.bookings.each_with_index do |booking, index| %>
            <tr>
              <td><%= index+1 %></td>
              <td><%= booking.user.name %></td>
              <td><button class="confirm-booking" data-id="<%= booking.id %>"><%= booking.status %></button></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
  </table>
<% end %>
</div>



<!-- if viewing your own user page, show all the classes you have booked -->
<% if current_user && current_user == @user %>
<div class="lessons-booked-header">
  <strong>You are booked in for the following courses:</strong>
  Once the instructor approves you to attend, your status will change to "confirmed". Check back after attending the class and check for a link to write a review of the lesson!
</div>

<div class="view-lessons-booked">
  <% if @bookings_as_client.empty? %>
    <p>You have not yet booked any lessons!</p>
  <% end  %>
  <% if @bookings_as_client.empty? == false %>
    
    <table class="table table-striped">
        <thead><h4>
            <tr>
                <th></th>
                <th>Lesson</th>
                <th>Booking Status</th>
            </tr>
        </thead>

          <tbody>
          <% @bookings_as_client.each_with_index do |booking, index| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= link_to booking.lesson.title, "/lessons/#{booking.lesson.id}" %><% if booking.status == "attended" %> - <em><%= link_to "write review", new_review_path %></em><% end %></td>
                <td><%= booking.status %></td>
              </tr>
          <% end %>
          </tbody>
    </table>
    
  <% end %>
</div>
<% end %>

app/views/welcomes/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  <% content_for :body do %>
  <body id="welcome">
    <title>GetFit</title>
    <% end %>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="https://s3-eu-west-1.amazonaws.com/fitnessproject/slide1.jpg" alt=" ">
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <img src="https://s3-eu-west-1.amazonaws.com/fitnessproject/slide2.jpg" alt="">
          <div class="carousel-caption">
          </div>
        </div>
          <div class="third item">
            <img src="https://s3-eu-west-1.amazonaws.com/fitnessproject/slide3.jpg" alt="">
            <div class="carousel-caption">
            </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

  </body>
</html>